//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qaroco.DL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Address
    {
        [DataMember]
        public int AddressId { get; set; }
        [DataMember]
        public Nullable<int> CityId { get; set; }
        [DataMember]
        public Nullable<int> DistrictId { get; set; }
        [DataMember]
        public string AddressContent { get; set; }
        [DataMember]
        public string AddressContent2 { get; set; }
    }
}
