//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qaroco.DL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class RegisterFolder
    {
        [DataMember]
        public int RFId { get; set; }
        [DataMember]
        public string FolderTitle { get; set; }
        [DataMember]
        public string FolderContent { get; set; }
        [DataMember]
        public Nullable<bool> FolderStatus { get; set; }
    }
}
